### ISSUE TITLE
update site does not allow install for 2019-06

### ISSUE THREAD

**Issue by big-chen** [netceteragroup/quickrex#7]
Hi,

could you please check the plugin for compatibility to eclipse 2019-06? We would like to use this great little plug-in further on...

I got the following errors:
No repository found containing: osgi.bundle,com.netcetera.eclipse.quickrex.plugin,4.3.0
No repository found containing: org.eclipse.update.feature,com.netcetera.eclipse.quickrex.feature,4.3.0

Thanks!

**Comment by marschall** [comment]
Sorry for the long delay. It looks like there was an issue with GitHub pages. I just verified it works with 2019-06 and 2021-12 with the following update site:

http://netceteragroup.github.io/quickrex/updatesite

**Comment by marschall** [comment]
Closing, assumed fixed.
