### ISSUE TITLE
hidden from marketplace because of http links

### ISSUE THREAD

**Issue by Bananeweizen** [netceteragroup/quickrex#8]
The plugin has been hidden from marketplace because of using http links: https://gitlab.eclipse.org/eclipsefdn/security/public-tasks/-/issues/1
Since it is already hosted on an https update site, it seems like it should be possible to fix this via mass search/replace.

**Comment by marschall** [comment]
I'm looking into it. The site itself does not seem to reference http://. However the entry seems to be completely gone from the market place.

**Comment by marschall** [comment]
https://gitlab.eclipse.org/eclipsefdn/it/websites/marketplace.eclipse.org/-/issues/125

**Comment by marschall** [comment]
It got purged because I didn't manage to find the correct credentials in time. I resubmitted it under https://marketplace.eclipse.org/content/quickrex and it's currently pending moderation.

**Comment by marschall** [comment]
Should be listed again https://marketplace.eclipse.org/content/quickrex
